# Bike Sharing Dataset

Bike sharing systems are a new generation of traditional bike rentals where the whole process from membership, rental, and return has become automatic.  
Through these systems, users can easily rent a bike from a particular location and return it at another. Currently, there are over 500 bike-sharing programs around the world, composed of over 500 thousand bicycles.  
Today, there is great interest in these systems due to their important role in traffic, environmental, and health issues.

Apart from the interesting real-world applications of bike sharing systems, the characteristics of the data generated by these systems make them attractive for research.  
Unlike other transport services such as buses or subways, the duration of travel, and departure and arrival positions are explicitly recorded.  
This feature turns the bike-sharing system into a virtual sensor network that can be used for sensing mobility in the city.  
Thus, it is expected that most important events in the city could be detected by monitoring this data.

---

## Data Set

The bike-sharing rental process is highly correlated with environmental and seasonal settings. For instance, weather conditions,  
precipitation, day of the week, season, hour of the day, etc., can affect rental behavior. The core dataset includes a two-year historical log for the years 2011 and 2012 from the Capital Bikeshare system in Washington D.C., USA.  
We aggregated the data on an hourly and daily basis and added the corresponding weather and seasonal information.

---

## Associated Tasks

- **Regression**:  
   Prediction of bike rental counts hourly based on environmental and seasonal settings.

---

## Dataset Characteristics

- **instant**: record index
- **dteday**: date
- **season**: season (1: spring, 2: summer, 3: fall, 4: winter)
- **yr**: year (0: 2011, 1: 2012)
- **mnth**: month (1 to 12)
- **hr**: hour (0 to 23)
- **holiday**: whether the day is a holiday (extracted from [holiday schedule](http://dchr.dc.gov/page/holiday-schedule))
- **weekday**: day of the week
- **workingday**: whether the day is a working day (1: if neither weekend nor holiday, 0: otherwise)
- **weathersit**:
  - 1: Clear, Few clouds, Partly cloudy
  - 2: Mist + Cloudy, Mist + Broken clouds, Mist + Few clouds
  - 3: Light Snow, Light Rain + Thunderstorm + Scattered clouds
  - 4: Heavy Rain + Ice Pallets + Thunderstorm + Mist, Snow + Fog
- **temp**: Normalized temperature in Celsius (values divided by 41, max)
- **atemp**: Normalized "feeling" temperature in Celsius (values divided by 50, max)
- **hum**: Normalized humidity (values divided by 100, max)
- **windspeed**: Normalized wind speed (values divided by 67, max)
- **casual**: count of casual users
- **registered**: count of registered users
- **cnt**: count of total rental bikes including both casual and registered
